### ISSUE TITLE
snake-case with multiple CAPS

### ISSUE THREAD

**Issue by sbitteker** [qerub/camel-snake-kebab#26]
When converting 

(->snake_case "XMLsettingsAndOtherThings")
"xm_lsettings_and_other_things"

Is there a way to convert it to "xml_settings_and_other_things"

Perhaps insert dashes on case change?

**Comment by qerub** [comment]
The output is strange because your input isn't proper camelCase because of the lower case "s" in the word "settings". An upper case "s" would have worked better:

```clojure
(->snake_case "XMLSettingsAndOtherThings")
; => "xml_settings_and_other_things"
(->snake_case "XmlSettingsAndOtherThings")
; => "xml_settings_and_other_things"
```

Now, I expect you don't control the input but since version 0.3.0 you can control how this library splits strings. Try this with a couple of more input strings and let me know if it works for you:

```clojure
(def my-word-separator #"(?<=[A-Z]{2,})(?=[^A-Z])|(?<=[^A-Z])(?=[A-Z])")
(->snake_case "XMLsettingsAndOtherThings" :separator my-word-separator)
; => "xml_settings_and_other_things"
```

**Comment by qerub** [comment]
Closing. Please reopen if you're not satisfied with the provided solution.
